version: '3.9'
services:
  blue:
    container_name: blue
    image: gamjajeon/gamjajeon-server
    ports:
      - "8080:8080"
    environment:
      PORT: ${PORT}
      DRIVER_NAME: ${DRIVER_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      DATABASE: ${DATABASE}
      HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}
      HIBERNATE_DIALECT: ${HIBERNATE_DIALECT}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_SECONDS: ${ACCESS_TOKEN_EXPIRE_SECONDS}
      REFRESH_TOKEN_EXPIRE_SECONDS: ${REFRESH_TOKEN_EXPIRE_SECONDS}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      LOG_PATH: ${LOG_PATH}
      HOST_PATH: ${HOST_PATH}
      CONTAINER_PATH: ${CONTAINER_PATH}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - "${HOST_PATH}:${CONTAINER_PATH}"

  green:
    container_name: green
    image: gamjajeon/gamjajeon-server
    ports:
      - "8081:8080"
    environment:
      PORT: ${PORT}
      DRIVER_NAME: ${DRIVER_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      DATABASE: ${DATABASE}
      HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}
      HIBERNATE_DIALECT: ${HIBERNATE_DIALECT}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_SECONDS: ${ACCESS_TOKEN_EXPIRE_SECONDS}
      REFRESH_TOKEN_EXPIRE_SECONDS: ${REFRESH_TOKEN_EXPIRE_SECONDS}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      LOG_PATH: ${LOG_PATH}
      HOST_PATH: ${HOST_PATH}
      CONTAINER_PATH: ${CONTAINER_PATH}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - "${HOST_PATH}:${CONTAINER_PATH}"