version: '3.9'
services:
  server:
    container_name: server
    image: pym0040/gamjajeon
    ports:
      - "80:8080"
    environment:
      DRIVER_NAME: ${DRIVER_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      DATABASE: ${DATABASE}
      HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}
      HIBERNATE_DIALECT: ${HIBERNATE_DIALECT}
      PORT: ${PORT}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_SECONDS: ${ACCESS_TOKEN_EXPIRE_SECONDS}
      REFRESH_TOKEN_EXPIRE_SECONDS: ${REFRESH_TOKEN_EXPIRE_SECONDS}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}