spring:
  config:
    import: ${ENV_PATH}

  # profile 설정
  profiles:
    group:
      local: local
      dev: dev
      prod: prod

    include:
      - db
      - security
      - cloud

  # 업로드 파일 크기 제한
  servlet:
    multipart:
      max-file-size: 5MB

server:
  port: ${PORT}
  shutdown: graceful
