spring:
  config:
    import: optional:file:.env[.properties]

  # profile 설정
  profiles:
    group:
      local: local
      dev: dev
      prod: prod

    include:
      - db

  # 업로드 파일 크기 제한
  servlet:
    multipart:
      max-file-size: 5MB

server:
  port: ${PORT}
  shutdown: graceful
