name: Develop Deploy

on:
  push:
    branches: [ develop ]

jobs:
  dev-deploy:
    runs-on: ubuntu-18.04

    steps:
      - run: echo "👉 Branch is ${{ github.ref }} and repository is ${{ github.repository }}"
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: echo "👉 Setting up JDK"
      - name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - run: echo "👉 Connect ssh and deploy the server"
      - name: Connect ssh
        uses: applyboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
          script: |
            cd /gamjajeon
            ./deploy.sh